export const DESKTOP_COMMANDS = {
  OPEN_PANE: 'OPEN_PANE',
  OPEN_CONVERSATION: 'OPEN_CONVERSATION',
  FOCUS_PANE: 'FOCUS_PANE',
  MINIMIZE_PANE: 'MINIMIZE_PANE',
  CLOSE_PANE: 'CLOSE_PANE',
  TOGGLE_START: 'TOGGLE_START',
  OPEN_CONTACTS: 'OPEN_CONTACTS'
};

export default DESKTOP_COMMANDS;
